import { FacetObject } from '../../components/facets';

export const statusFacet: FacetObject = {
  label: 'Status',
  name: 'reviewed',
  allowMultipleSelection: false,
  values: [
    { label: 'Unreviewed (TrEMBL)', value: 'false', count: 1271454 },
    { label: 'Reviewed (Swiss-Prot)', value: 'true', count: 11729 },
  ],
};

export const proteinsWithFacet: FacetObject = {
  label: 'Proteins with',
  name: 'proteins_with',
  allowMultipleSelection: true,
  values: [
    { label: '3D structure', value: '3dstructure', count: 1858 },
    { label: 'Active site', value: 'act_site', count: 386659 },
    {
      label: 'Activity regulation',
      value: 'activity_regulation',
      count: 30848,
    },
    { label: 'Allergen', value: 'allergen', count: 21 },
    {
      label: 'Alternative products(isoforms)',
      value: 'alternative_products',
      count: 1066,
    },
    { label: 'Binding site', value: 'binding', count: 341556 },
    {
      label: 'Biophysicochemical properties',
      value: 'biophysicochemical_properties',
      count: 1054,
    },
    { label: 'Biotechnological use', value: 'biotechnology', count: 52 },
    { label: 'Calcium binding', value: 'ca_bind', count: 798 },
    { label: 'Glycosylation', value: 'carbohyd', count: 5546 },
    {
      label: 'Catalytic activity',
      value: 'catalytic_activity',
      count: 794168,
    },
    { label: 'Chain', value: 'chain', count: 85391 },
    { label: 'Cofactors', value: 'cofactor', count: 363994 },
    { label: 'Coiled-coil', value: 'coiled', count: 59317 },
    { label: 'Compositional bias', value: 'compbias', count: 62989 },
    { label: 'Cross-link', value: 'crosslnk', count: 544 },
    {
      label: 'Developmental stage',
      value: 'developmental_stage',
      count: 568,
    },
    { label: 'Disease', value: 'disease', count: 365 },
    {
      label: 'Disruption phenotype',
      value: 'disruption_phenotype',
      count: 1009,
    },
    { label: 'Disulfide bond', value: 'disulfid', count: 3843 },
    { label: 'DNA binding', value: 'dna_bind', count: 1247 },
    { label: 'Domain', value: 'domain', count: 881690 },
    { label: 'Function', value: 'function', count: 415413 },
    { label: 'Helix', value: 'helix', count: 1372 },
    { label: 'Induction', value: 'induction', count: 1459 },
    { label: 'Initiator methionine', value: 'init_met', count: 766 },
    { label: 'Binary interaction', value: 'interaction', count: 1218 },
    { label: 'Intramembrane', value: 'intramem', count: 67 },
    { label: 'Lipidation', value: 'lipid', count: 310 },
    { label: 'Mass spectrometry', value: 'mass_spectrometry', count: 115 },
    { label: 'Metal binding', value: 'metal', count: 108413 },
    { label: 'Modified residue', value: 'mod_res', count: 37292 },
    { label: 'Motif', value: 'motif', count: 1182 },
    { label: 'Mutagenesis', value: 'mutagen', count: 1173 },
    { label: 'Non-standard residue', value: 'non_std', count: 21 },
    { label: 'Nucleotide binding', value: 'np_bind', count: 174651 },
    {
      label:
        'Pathwayfacet.uniprot.proteins_with.value.subunit=Subunit structure',
      value: 'pathway',
      count: 517535,
    },
    { label: 'Peptide', value: 'peptide', count: 296 },
    { label: 'Pharmaceutical use', value: 'pharmaceutical', count: 11 },
    { label: 'Polymorphism', value: 'polymorphism', count: 75 },
    { label: 'Propeptide', value: 'propep', count: 461 },
    { label: 'PTM comments', value: 'ptm', count: 10630 },
    { label: 'Region', value: 'region', count: 330801 },
    { label: 'Repeat', value: 'repeat', count: 4063 },
    { label: 'RNA editing', value: 'rna_editing', count: 2 },
    { label: 'Signal peptide', value: 'signal', count: 75615 },
    { label: 'Beta strand', value: 'strand', count: 1298 },
    {
      label: 'Subcellular location',
      value: 'subcellular_location',
      count: 266948,
    },
    { value: 'subunit', count: 235350 },
    { label: 'Tissue specificity', value: 'tissue_specificity', count: 2194 },
    { label: 'Topological domain', value: 'topo_dom', count: 1078 },
    { label: 'Toxic dose', value: 'toxic_dose', count: 10 },
    { label: 'Transit peptide', value: 'transit', count: 356 },
    { label: 'Transmembrane', value: 'transmem', count: 121070 },
    { label: 'Turn', value: 'turn', count: 1173 },
    { label: 'Alternative splicing', value: 'var_seq', count: 997 },
    { label: 'Natural variant', value: 'variant', count: 789 },
    { label: 'Zinc finger', value: 'zn_fing', count: 445 },
  ],
};

export const facets: FacetObject[] = [
  statusFacet,
  {
    label: 'Model organisms',
    name: 'model_organism',
    allowMultipleSelection: true,
    values: [
      { value: 'Human', count: 1470 },
      { value: 'Mouse', count: 1261 },
      { value: 'A. thaliana', count: 1239 },
      { value: 'Rat', count: 1030 },
      { value: 'Rice', count: 646 },
    ],
  },
  proteinsWithFacet,
  {
    label: 'Protein Existence',
    name: 'existence',
    allowMultipleSelection: true,
    values: [
      { value: 'HOMOLOGY', count: 1000254 },
      { value: 'PREDICTED', count: 261161 },
      { value: 'TRANSCRIPT_LEVEL', count: 15049 },
      { value: 'PROTEIN_LEVEL', count: 6700 },
      { value: 'UNCERTAIN', count: 19 },
    ],
  },
  {
    label: 'Annotation Score',
    name: 'annotation_score',
    allowMultipleSelection: true,
    values: [
      { value: '2', count: 683263 },
      { value: '1', count: 377015 },
      { value: '3', count: 175410 },
      { value: '4', count: 39819 },
      { value: '5', count: 7676 },
    ],
  },
  {
    label: 'Sequence length',
    name: 'length',
    allowMultipleSelection: true,
    values: [
      { label: '1 - 200', value: '[1 TO 200]', count: 101062 },
      { label: '201 - 400', value: '[201 TO 400]', count: 553257 },
      { label: '401 - 600', value: '[401 TO 600]', count: 423158 },
      { label: '601 - 800', value: '[601 TO 800]', count: 120501 },
      { label: '>= 801', value: '[801 TO *]', count: 85205 },
    ],
  },
];

export default facets;
