/**
 * Used to type components generated by the "@svgr/webpack" loader
 */

// eslint-disable-next-line @typescript-eslint/no-empty-interface
interface SvgrComponent
  extends React.StatelessComponent<React.SVGAttributes<SVGElement>> {}

declare module '*.svg' {
  const content: SvgrComponent;
  export default content;
}
