import React from 'react';
import PropTypes from 'prop-types';
import { Link, useLocation } from 'react-router-dom';
import qs from 'query-string';

import ExpandableList from './expandable-list';

import { formatLargeNumber } from '../utils';

import '../styles/components/facets.scss';

/**
 * Takes a search string and parse it, handle facets specifically, keeps them
 * as sets of values
 * @param {string} string
 */
const parse = string => {
  const parsed = qs.parse(string);
  if (!parsed.facets) {
    return parsed;
  }
  const facets = (parsed.facets || '')
    .split(',')
    .map(stringTuple => stringTuple.split(':'));
  parsed.facets = {};
  // eslint-disable-next-line no-restricted-syntax
  for (const [name, value] of facets) {
    if (!parsed.facets[name]) {
      parsed.facets[name] = new Set();
    }
    parsed.facets[name].add(value);
  }
  return parsed;
};

/**
 * Takes a parsed search object (as generated by the previous "parse" function)
 * and generate a search string
 * @param {object} parsedSearch
 */
const stringify = ({ facets = {}, ...rest }) => {
  const facetString = Object.entries(facets)
    .map(([name, values]) =>
      Array.from(values).map(value => `${name}:${value}`)
    )
    .flat()
    .join(',');
  if (!facetString) {
    return qs.stringify(rest, { encode: false });
  }
  return qs.stringify({ ...rest, facets: facetString }, { encode: false });
};

const Facets = ({ data, extraActionsFor }) => {
  const location = useLocation();

  if (!(data && data.length)) {
    return null;
  }

  const facetsToShow = data.filter(
    facet => facet.values && facet.values.length
  );

  const search = parse(location.search);

  return (
    <div className="facets">
      <ul className="no-bullet">
        {facetsToShow.map(facet => (
          <li key={facet.name}>
            <div className="facet-name">{facet.label || facet.name}</div>
            <ExpandableList extraActions={extraActionsFor.get(facet.name)}>
              {facet.values.map(({ value, label, count }) => {
                const isActive =
                  search.facets &&
                  search.facets[facet.name] &&
                  search.facets[facet.name].has(value);

                const facetSet = new Set(
                  facet.allowMultipleSelection
                    ? (search.facets || {})[facet.name]
                    : null
                );
                facetSet[isActive ? 'delete' : 'add'](value);

                const to = {
                  ...location,
                  search: stringify({
                    ...search,
                    facets: { ...search.facets, [facet.name]: facetSet },
                  }),
                };

                return {
                  id: `${facet.name}_${value}`,
                  content: (
                    <Link
                      to={to}
                      className={isActive ? 'facet-active' : undefined}
                      replace
                    >
                      {`${label || value} (${formatLargeNumber(count)})`}
                    </Link>
                  ),
                };
              })}
            </ExpandableList>
          </li>
        ))}
      </ul>
    </div>
  );
};

Facets.propTypes = {
  /**
   * The facet data to be displayed
   */
  data: PropTypes.arrayOf(PropTypes.object).isRequired,
  /**
   * Extra components to be added in the "action" area, map of <facet name, component>
   */
  extraActionsFor: PropTypes.instanceOf(Map),
};

Facets.defaultProps = {
  extraActionsFor: new Map(),
};

export default Facets;
